### PR TITLE
3D models with Armor/Shells

### PR DESCRIPTION
**Pull request by r3n33**
This PR contains an alternate set of visual and collision models with a mix of v2 and v3 3D printable shells/armor.

### CODE REVIEW

**Comment by costashatz** [comment]
Will you not update the README?

**Comment by r3n33** [comment]
I had plans to add to the README later but I could do that now and resubmit.

**Comment by costashatz** [comment]
You do not have to close the PR. Push commits to your branch and they are automatically linked to the PR! ;)

**Comment by r3n33** [comment]
Very cool!

**Comment by costashatz** [comment]
Seems **ok**!

I like these new models!

**Pull request merged**
